server:
  port: 8082

dubbo:
  application:
    name: dubbo-service-consumer
  registry:
    address: zookeeper://192.168.10.112:2181?backup=192.168.10.25:2181,192.168.10.46:2181
  config-center:
    timeout: 60000