server:
  port: 8081

# actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"

# file upload limits
spring:
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
  #redis configuration
  redis:
    database: 1 #Redis数据库索引（默认为0）
    host: 192.168.10.131
    port: 6379
    password:
    max-wait: 300000 #连接池最大阻塞时间（使用负值表示没有限制）
    max-active: 100 #连接池最大连接数（使用负值表示没有限制）
    max-idle: 20 #连接池中的最大空闲连接
    min-idle: 0 #连接池中的最小空闲连接
    timeout: 3000 #连接超时
    expire-time: 10
  #mysql configuration
  datasource:
    url: jdbc:mysql://192.168.10.131:3306/ruoyi?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: ryuser
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  #rabbitMQ configuration
  rabbitmq:
    host: 192.168.10.131
    port: 5672
    username: nickel
    password: ironpearl
    virtual-host: rabbitmq-nickel
    publisher-confirms: true
    publisher-returns: true

    queue1: topic.man
    queue2: topic.woman
    exchange: topic.exchange
  #cache configuration with using redis
  cache:
    redis:
      time-to-live: 600000

es:
  host: 192.168.10.131
  port: 9200
  scheme: http

mybatis:
  type-aliases-package: com.jetsen.entity

apache:
  zookeeper:
    #host: 192.168.10.131:2181,192.168.10.131:2182,192.168.10.131:2183
    host: 192.168.10.131:2181
    maxRetry: 3
    sessionTimeout: 600000
    connectionTimeout: 10000
    namespace: jetsen.com
    auth: nickel:ironpearl

dubbo:
  application:
    name: dubbo-service-provider
  registry:
    address: zookeeper://192.168.10.131:2181?backup=192.168.10.39:2181,192.168.10.44:2181
  protocol:
    name: dubbo
    port: 20880
  config-center:
    timeout: 60000